export const LIBYAN_CITIES = [
  { value: "tripoli", label: "طرابلس" },
  { value: "benghazi", label: "بنغازي" },
  { value: "misrata", label: "مصراتة" },
  { value: "zawiya", label: "الزاوية" },
  { value: "bayda", label: "البيضاء" },
  { value: "ajdabiya", label: "أجدابيا" },
  { value: "khoms", label: "الخمس" },
  { value: "derna", label: "درنة" },
  { value: "tobruk", label: "طبرق" },
  { value: "sabha", label: "سبها" },
  { value: "sirte", label: "سرت" },
  { value: "gharyan", label: "غريان" },
  { value: "zliten", label: "زليتن" },
  { value: "sabratha", label: "صبراتة" },
  { value: "ubari", label: "أوباري" },
  { value: "bani-walid", label: "بني وليد" },
  { value: "tarhuna", label: "ترهونة" },
  { value: "zintan", label: "الزنتان" },
  { value: "nalut", label: "نالوت" },
  { value: "ghat", label: "غات" },
  { value: "murzuq", label: "مرزق" },
  { value: "janzur", label: "جنزور" },
  { value: "tajoura", label: "تاجوراء" },
  { value: "garabulli", label: "القره بوللي" },
  { value: "other", label: "أخرى" },
] as const;

export type LibyanCity = (typeof LIBYAN_CITIES)[number]["value"];
